reports:
  revenue:
    username: revenue@maibaloc.com
    password: samplepassrev
    files:
    - K21_Revenues_Report
  
  martketing:
    username: mkt@maibaloc.com
    password: samplepassmkt
    files:
    - K21_Marketing_Report
    - K21_Ads_Report