report_folder_path: "D:\\demo"

reports:
  revenue:
    username: revenue@katalina.com
    password: samplepassrev
    files:
    - K21_Revenues_Report
  
  martketing:
    username: mkt@katalina.com
    password: samplepassmkt
    files:
    - K21_Marketing_Report
    - K21_Ads_Report